# This is a basic workflow to help you get started with Actions

name: Lint, Test and Promote

# Controls when the action will run. Triggers the workflow on push
# events but only for the main branch or pull request
on:
  push:
    branches:
      - main
      - devel
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  shell_lint:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # replace "master" with any valid ref
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          severity: "error"

  promote:
    if: github.ref == 'refs/heads/devel'
    runs-on: ubuntu-latest
    needs: [shell_lint]
    steps:
      - uses: actions/checkout@v2
        # TODO: Break out into common bits - perhaps even the "uses" type system.
      - name: Merge to master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: devel
          target_branch: main
          github_token: ${{ github.token }}

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4.6
        with:
          release_branches: devel
          tag_prefix: ''
          github_token: ${{ secrets.GITHUB_TOKEN }}
